output_folder: "/expanse/lustre/projects/<<EXPANSEPROJECT>>/<<USER>>/CIP_examples/example10_out/"

scripts_folder: "/home/<<USER>>/a/demos/amber/workshop/scripts/"

project_folder: "/home/<<USER>>/a/demos/amber/workshop_amber/example_04"

inputs_list: "/home/<<USER>>/a/CIP_Nextflow_on_HPC/examples/nextflow_slurm/example10_amber_cpu_gpu/inputs.yml"