output_folder: "/home/hgrabski/a/CIP_Nextflow_on_HPC/examples/nextflow_slurm/example8_out/"

project_folders:
  - /home/hgrabski/a/demos/gromacs/water-cut1.0_GMX50_bare/1536
  - /home/hgrabski/a/demos/gromacs/water-cut1.0_GMX50_bare/3072


