output_folder:  "/expanse/lustre/projects/<<EXPANSEPROJECT>>/<<USER>>/CIP_examples/example8_out/"

project_folders:
  - /home/<<USER>>/a/demos/gromacs/water-cut1.0_GMX50_bare/1536
  - /home/<<USER>>/a/demos/gromacs/water-cut1.0_GMX50_bare/3072


